# Generated by Django 5.1.3 on 2024-11-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customer_remove_orders_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
    ]
